#!/bin/bash

VERSION=latest
OS=alpine
PLATFORMS=linux/arm/v7,linux/amd64

case "$#" in
  "0" )
    echo -e "$(basename $0) <os> [version] [platforms]\n"
    echo "OSes and platforms must be separated by commas."
    echo "If not specified, default version is 'latest'."
    exit 0
    ;;
  "1" )
    OS=$1
    ;;
  "2" )
    OS=$1
    VERSION=$2
    ;;
  "3" )
    OS=$1
    VERSION=$2
    PLATFORMS=$3
    ;;
  * )
    echo "Wrong number of arguments."
    exit 0
esac

source "./helpers/git-tags"

if [ "$VERSION" == "latest" ]; then
  TAG=$(git-latest-tag openresty openresty | cut -c2-)
else
  TAG=$(git-check-tag openresty openresty ${VERSION} | cut -c2-)
fi

NPROC=$(nproc)

echo "Build version $VERSION ($TAG) for $OS (building with $NPROC processors)"

for os in $(echo $OS|tr ',' ' ')
do
  echo "Currently building with this base image : $os ..."

  pushd $os
  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  docker buildx create --name builder --driver docker-container --use
  docker buildx inspect --bootstrap

  for flavor in $(ls -1 *.dockerfile|cut -d'.' -f1)
  do
    TAG_LATEST=''
    if [[ "$VERSION" == "latest" ]]; then
      TAG_LATEST="-t oorabona/${flavor}:latest"
    fi

    echo "Building image '$flavor' ..."
    docker buildx build --push --build-arg RESTY_J=${NPROC} --build-arg RESTY_VERSION=${TAG} --platform=${PLATFORMS} -f ${flavor}.dockerfile -t oorabona/${flavor}:${TAG} ${TAG_LATEST} .
  done

  docker buildx rm builder
  popd

done

echo "Completed build !"
exit 1
