#!/usr/bin/env bash

VERSION=latest
FLAVORS=all
PLATFORMS=linux/arm/v7,linux/amd64

case "$#" in
  "0" )
    echo -e "$(basename $0) <OSes> [flavors] [version] [platforms]\n"
    echo "OSes, flavors and platforms must be separated by commas."
    echo "If you want to specify version and/or platforms and you want to build all flavors, use 'all'."
    echo "If not specified, default version is 'latest'."
    echo "If not specified, all flavors for a specific OS are built."
    echo "If not specified, $(echo "${PLATFORMS%,*} and ${PLATFORMS##*,}") are built, 'all' is accepted."
    exit 1
    ;;
  "1" )
    OS=$1
    ;;
  "2" )
    OS=$1
    FLAVORS=$2
    ;;
  "3" )
    OS=$1
    FLAVORS=$2
    VERSION=$3
    ;;
  "4" )
    OS=$1
    FLAVORS=$2
    VERSION=$3
    PLATFORMS=$4
    ;;
  * )
    echo "Wrong number of arguments."
    exit 1
esac

source "./helpers/git-tags"

if [[ -z "$TAG" ]]; then
  echo "User did not provide any tag, try to guess it."
  if [ "$VERSION" == "latest" ]; then
    TAG=$(git_latest_tag openresty openresty | cut -c2-)
  else
    TAG=$(git_check_tag openresty openresty ${VERSION} | cut -c2-)
  fi
else
  echo "Using user provided tag: $TAG"
fi

if [[ -z "$TAG" ]]; then
  echo "No tag or branch found. Aborting."
  exit 1
fi

NPROC=${NPROC:-$(nproc)}

echo "Build version $VERSION ($TAG) for $OS (building with $NPROC processors)"

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name builder --driver docker-container --use
docker buildx inspect --bootstrap

for os in $(echo $OS|tr ',' ' ')
do
  echo "Currently building with this base image : $os ..."

  if [ "$FLAVORS" == "all" ]; then
    flavors=$(grep -Po "AS openresty-\K[a-z]+$" ${os}.dockerfile)
  else
    flavors=$(echo $FLAVORS|tr ',' ' ')
  fi

  for flavor in ${flavors}
  do
    TAG_LATEST=''
    if [[ "$VERSION" == "latest" ]]; then
      TAG_LATEST="-t oorabona/openresty-${flavor}-${os}:latest"
    fi

    echo "Building image '$flavor' ..."
    docker buildx build --push --build-arg RESTY_J=${NPROC} --build-arg RESTY_VERSION=${TAG} --build-arg RESTY_FLAVOR=${flavor} --platform=${PLATFORMS} -f ${os}.dockerfile -t oorabona/openresty-${flavor}-${os}:${TAG} ${TAG_LATEST} .
  done

done

docker buildx rm builder

echo "Completed build !"
exit 0
